services:
  - type: web
    plan: free
    name: rido-api
    env: python
    buildCommand: pip3 install -r requirements.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    healthCheckPath: /docs
